Feature/complete aboutpage
octue/planex-site pull request #59
Opened 2021-07-22 17:52 UTC by muhammadqamar

## Summary

updated home and about us page 

## Quality Checklist

- [ ] New features are fully tested (No matter how much Coverage Karma you have)
- [ ] **[v0.2 onward]** New features are included in the documentation
- [ ] **[v0.2 onward]** Breaking changes are documented with clear instructions of what 

### Coverage Karma

- [ ] If your PR decreases test coverage, do you feel you have built enough `Coverage Karma`* to justify it?

*Coverage Karma can be earned by disproportionally increasing test coverage in the rest of your contributions.
It's an honesty policy - you keep count of your own.

2021-07-23 09:02 UTC, thclark requested changes
@muhammadqamar please find attached a review of suggested changes, mostly extremely good, thank you - the majority of the changes are extremely minor.

I've realised that I made a mistake and didn't push some code that wired up the font correctly, and also contains a couple of points where I override the typography in the theme, there are a couple of comments where I suggest that so if you pull `feature/new-design` and merge it into your current branch, I think you'll find that helpful.

2021-07-25 11:15 UTC, muhammadqamar commented on src/components/hexagon/HexagonSvg.jsx
> +  hexagonMB: {
I have expanded the word “MB” to full name (change only this page. Should i change in every pages).
on some places I have use this word which is mean “For Mobile View”

2021-07-25 11:19 UTC, muhammadqamar commented on src/components/sectionelements/sectionwithhexagon/HexagonSection.jsx
> +const HexagonSection = () => {
Changed the component name (Covert "HexagonSection" to "MianPageHexagonSection" )

2021-07-25 11:20 UTC, muhammadqamar commented on src/components/sectionelements/sectionwithhexagon/AboutHexagonSection.jsx
> +                  OIn 2021, Octue became a non-profit dedicated to developing
Removed the First Character

2021-07-25 11:24 UTC, muhammadqamar commented on src/components/hexagon/HexagonSvg.jsx
> +  // }
I have Removed these comments

2021-07-25 11:30 UTC, muhammadqamar commented on src/components/hexagon/HexagonSvg.jsx
Reintroduce propTypes and DefaultProps has been Done

2021-07-25 11:33 UTC, muhammadqamar commented on src/components/hexagon/MultipleHexagonWithImage.jsx
> +
Removed extra line

2021-07-25 11:46 UTC, muhammadqamar commented on src/components/hexagon/MultipleHexagonWithImage.jsx
> +        <SimpleHexagon bgHexagomImg={image} bgX="10%" bgY="20%" />
Changed the name to "bgHexImg"

2021-07-25 12:08 UTC, muhammadqamar commented on src/components/hexagon/SimpleSmallHexagon.jsx
> +    // padding: '6px',
Cleaned the comments

2021-07-25 12:09 UTC, muhammadqamar commented on src/components/hexagon/SimpleSmallHexagon.jsx
> +  bgHexagomImg: BackgroundImage,
Solved

2021-07-25 12:17 UTC, muhammadqamar commented on src/components/sectionelements/SectionDetailW3.jsx
> +const SectionDetailW3 = ({ headingOne, headingTwo, description }) => {
This Function Name "SectionDetailW3" has been Converted to "SectionDetailWithTwoHeading"

2021-07-25 12:17 UTC, muhammadqamar commented on src/components/sectionelements/SectionElement.stories.jsx
> +export default {
Solved

2021-07-25 12:18 UTC, muhammadqamar commented on src/components/sectionelements/SectionElement.stories.jsx
> +"
Removed

2021-07-25 12:32 UTC, muhammadqamar commented on src/components/sectionelements/sectionwithhexagon/HexagonSection.jsx
> +            /> */}
Removed

2021-07-25 12:34 UTC, muhammadqamar commented on src/legacy/fields/fieldsStyle.jsx
> +      // fontFamily: '"Roboto Slab", "Times New Roman", serif',
Removed

2021-07-25 12:58 UTC, muhammadqamar commented on src/components/sectionelements/SectionHeading.jsx
> +        <Typography variant="h1" component="h1" className={classes.title}>
Component='h1' changed to Component='h2'

2021-07-26 07:24 UTC, muhammadqamar commented on package.json
> +    "release": "standard-version"
Removed "release": "standard-version"

2021-07-26 07:24 UTC, muhammadqamar commented on package.json
> +    "standard-version": "^9.3.1"
Removed standard-version

2021-07-26 07:30 UTC, muhammadqamar commented on src/components/hexagon/SimpleHexagon.jsx
>      <>
Removed unnecessary fragments

2021-07-27 08:09 UTC, thclark commented
Hi @muhammadqamar there's still a couple of unresolved issues here outstanding before I can pull into main, can you fix these up before progressing on other PRs please? That way I can look at other PRS without all these contents in.
Thanks!

2021-07-27 09:44 UTC, muhammadqamar commented on package.json
> +  "version": "0.1.6",
Reverted to version": "0.1.1

2021-07-27 13:36 UTC, muhammadqamar commented on src/components/hexagon/HexagonSvg.jsx
> +      <Box className={`${classes.wrapIcon} ${classes.hexagonMB}`}>
Done

2021-07-27 13:42 UTC, muhammadqamar commented on CHANGELOG.md
> +# Changelog
Removed

2021-07-27 14:22 UTC, thclark commented on src/components/sectionelements/herosection/HeroSection.jsx
> +    // whiteSpace: 'pre-line',
It needs to be one of the recognised [mui typography variants](https://material-ui.com/components/typography/#component) ‘subtitle’ isn’t one, so the classes won’t get picked up.

2021-07-27 14:26 UTC, thclark commented on src/components/sectionelements/herosection/HeroSection.jsx
> +    // whiteSpace: 'pre-line',
Looks like body2 and subtitle1 are both available ([see here](https://github.com/octue/planex-site/blob/eed6568dde6ef2958c94e5d443429cc028c25b29/src/themes/_base.js#L106))

2021-07-27 14:44 UTC, muhammadqamar commented on src/components/sectionelements/herosection/HeroSection.jsx
> +    // whiteSpace: 'pre-line',
But the property mentioned in theme were not matching according to figma design.

2021-07-27 14:48 UTC, thclark commented on src/components/sectionelements/herosection/HeroSection.jsx
> +    // whiteSpace: 'pre-line',
@muhammadqamar hang on, let me show you what I mean. Give me 15 mins!

2021-07-28 11:47 UTC, thclark commented on src/components/sectionelements/herosection/HeroSection.jsx
> +    lineHeight: '88px',
Covered in #63 so will resolve just now

2021-07-28 11:47 UTC, thclark commented on src/components/sectionelements/herosection/HeroSection.jsx
> +    // whiteSpace: 'pre-line',
Covered in #63 so will resolve just now

2021-07-28 11:49 UTC, thclark commented on CHANGELOG.md
> +# Changelog
It didn't get removed; done myself in #16a9d13

2021-07-28 11:53 UTC, merged