Feature/getinvolved page
octue/planex-site pull request #73
Opened 2021-08-05 15:21 UTC by muhammadqamar

## Summary

Adding Two Pages (Articles and Get Involved-A)
Apply Hexagon Grid in Different Pages

## Quality Checklist

- [ ] New features are fully tested (No matter how much Coverage Karma you have)
- [ ] **[v0.2 onward]** New features are included in the documentation
- [ ] **[v0.2 onward]** Breaking changes are documented with clear instructions of what 

### Coverage Karma

- [ ] If your PR decreases test coverage, do you feel you have built enough `Coverage Karma`* to justify it?

*Coverage Karma can be earned by disproportionally increasing test coverage in the rest of your contributions.
It's an honesty policy - you keep count of your own.

2021-08-05 19:02 UTC, thclark requested changes
Main change is a need for pagination on the articles page

2021-08-05 19:02 UTC, thclark commented on src/components/sectionelements/helpsection/HelpSection.jsx
> +              {/* <TripleHexagon image={Image} /> */}
Remove the comment. We have a shiny new HexagonGrid now ;)

2021-08-05 19:02 UTC, thclark commented on src/components/sectionelements/sectionwithhexagon/AboutHexagonSection.jsx
> +              {/* <MultipleHexagonWithImage image={Image} /> */}
remove comment

2021-08-05 19:02 UTC, thclark commented on src/components/sectionelements/sectionwithhexagon/consultancyHexagonsections/DigitalHexagonSection.jsx
> +              {/* <MultipleHexagonWithImage image={Image} /> */}
comment

2021-08-05 19:02 UTC, thclark commented on src/components/sectionelements/sectionwithhexagon/consultancyHexagonsections/StrategyHexagonSection.jsx
> +              {/* <ReverseMultipleHexagonImage image={Image} /> */}
comment

2021-08-05 19:02 UTC, thclark commented on src/components/sectionelements/sectionwithhexagon/consultancyHexagonsections/SupportHexagonSection.jsx
> +              {/* <MultipleHexagonWithImage image={Image} /> */}
comment

2021-08-06 11:17 UTC, muhammadqamar commented on src/components/sectionelements/articlessection/LatestArticlesSection.jsx
> +              </Typography>
How many articles will display in this page

2021-08-06 13:18 UTC, thclark commented on src/components/sectionelements/articlessection/LatestArticlesSection.jsx
> +              </Typography>
Let’s take the lead from the designer and put 6 articles on the page

2021-08-07 07:51 UTC, merged